# Generated by Django 6.0.6 on 2026-07-05 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-is_done', '-created_at')},
        ),
    ]
