# Generated by Django 6.0.6 on 2026-07-05 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('is_done', '-created_at')},
        ),
    ]
